// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnpjygumhwdtekjddegk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhucGp5Z3VtaHdkdGVramRkZWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzE3NTAsImV4cCI6MjA3MjMwNzc1MH0.d17Q_SCbZb7vTsYtHd3-Rdh13u8aies4xZx6B7JcXiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});